#%RAML 1.0 NamedExample
value:
    "order_id": 10003
    "store_id": 3341
    "store_name": "Dallas Neighborhood Market"
    "store_address": "2305 N Central Expy, Dallas, TX, US (75204)"
    "store_distance": 0.43
    "store_contact_number": "214-953-0460"
    "product_type_id": "3L0GJRKXI29E"
    "quantity": 10