#%RAML 1.0 NamedExample
productDetails:
  [
	{
        "productByProductIdHolidays": {
            "offerCount": 1,
            "transactableOfferCount": 1,
            "bundleType": "ITEM",
            "sellerList": [
                {
                    "catalogSellerId": "0",
                    "sellerName": "Walmart.com",
                    "sellerDisplayName": "Walmart.com",
                    "sellerId": "F55CDC31AB754BB68FE0B39041159D63",
                    "sellerType": "INTERNAL"
                }
            ],
            "regularItem": true,
            "productType": "Mouthwash",
            "offers": [
                "DCFFA990DE7241A8A07014C4C3E880A1"
            ],
            "productId": "74PHT29UCA07",
            "productAttributes": {
                "manufacturerName": "Procter & Gamble",
                "numberOfReviews": 99,
                "ironbankCategory": "Beauty, Personal Care, & Hygiene",
                "productName": "Crest Scope Outlast Mouthwash, Long Lasting Mint, 1 L, 2 Pack",
                "productCategory": {
                    "path": [
                        {
                            "name": "Personal Care",
                            "url": "/cp/1005862"
                        },
                        {
                            "name": "Oral Care",
                            "url": "/cp/1007221"
                        },
                        {
                            "name": "Mouthwash",
                            "url": "/cp/1007360"
                        },
                        {
                            "name": "Dry Mouth Mouthwash",
                            "url": "/cp/8361519"
                        },
                        {
                            "name": "All Dry Mouth Mouthwash",
                            "url": "/cp/5654027"
                        }
                    ],
                    "categoryPathId": "0:1005862:1007221:1007360:8361519:5654027",
                    "categoryPath": "Home Page/Personal Care/Oral Care/Mouthwash/Dry Mouth Mouthwash/All Dry Mouth Mouthwash"
                },
                "classId": "1",
                "walmartEGiftCard": false,
                "productClassification": {},
                "manufacturerProductId": "00037000771128",
                "verticalInfo": {
                    "verticalId": "standard",
                    "verticalTheme": "standard",
                    "walledGarden": false
                },
                "averageRating": 4.8,
                "karfIsAlcohol": "No",
                "model": "3700077112",
                "rhPath": "40000:43000:43005:43117:43279",
                "brand": "Scope",
                "legalAttributes": {},
                "canonicalUrl": "/ip/Crest-Scope-Outlast-Mouthwash-Long-Lasting-Mint-1-L-2-Pack/384035170",
                "shortDescription": "<ul><li>Keeps breath feeling fresh up to 5x longer‡ ‡ vs. brushing alone</li><li>Speak confidently with the #1 fresh breath brand among non-drug mouthwashes** **P&G Calculation based on Nielsen US reported sales for year ending w/o 1/10/2015</li><li>Crest clean meets Scope freshness</li></ul>",
                "productDietaryAttributes": [
                    {
                        "key": "organic_certifications",
                        "values": [
                            "N/A"
                        ]
                    }
                ],
                "detailedDescription": "<ul><li>Keeps breath feeling fresh up to 5x longer‡ ‡ vs. brushing alone</li><li>Speak confidently with the #1 fresh breath brand among non-drug mouthwashes** **P&G Calculation based on Nielsen US reported sales for year ending w/o 1/10/2015</li><li>Crest clean meets Scope freshness</li><li>Kills 99% of bad breath germs in lab tests</li><li>Long Lasting Mint Flavor</li></ul>",
                "movieAttributes": {
                    "numberOfCustRatings": "99"
                },
                "walmartItemNumber": "566184452",
                "walmartGiftCard": false,
                "primaryShelfId": "5654027",
                "specialityGiftCard": false,
                "classType": "REGULAR"
            },
            "upc": "037000771128",
            "primaryProductId": "74PHT29UCA07",
            "productSegment": "Health & Beauty",
            "productTypeId": "1240",
            "btvAvailable": false,
            "usItemId": "384035170",
            "consumable": true,
            "offerList": [
                {
                    "productAvailability": {
                        "availabilityStatus": "IN_STOCK"
                    },
                    "offerInfo": {
                        "offerType": "ONLINE_AND_STORE",
                        "quantityOptions": {
                            "orderLimit": 12,
                            "orderMinLimit": 1
                        },
                        "preorderInfo": {},
                        "offerId": "DCFFA990DE7241A8A07014C4C3E880A1",
                        "offerMarketAttributes": {},
                        "showSoldBy": false
                    },
                    "pricesInfo": {
                        "prices": {
                            "current": {
                                "price": 6.97,
                                "priceType": "BASE",
                                "currencyUnitSymbol": "$",
                                "currencyUnit": "USD"
                            },
                            "unit": {
                                "unitOfMeasure": "FLUID_OUNCE",
                                "price": 0.103,
                                "priceType": "BASE",
                                "currencyUnitSymbol": "$",
                                "currencyUnit": "USD"
                            },
                            "variableUnit": {
                                "price": 6.97,
                                "currencyUnitSymbol": "$",
                                "currencyUnit": "USD"
                            }
                        },
                        "priceDisplayCodes": {
                            "rollback": false,
                            "hidePriceForSOI": false,
                            "unitPriceDisplayCondition": "(10.3 ¢/fl oz)",
                            "reducedPrice": false,
                            "eligibleForAssociateDiscount": true,
                            "clearance": false,
                            "strikethrough": false
                        }
                    },
                    "giftingOptions": {
                        "giftOverboxEligible": true,
                        "priceSuppressionInd": true,
                        "giftingEligibilityInd": true,
                        "reasonCode": "Own_DSV_Store",
                        "giftMessageEligible": true,
                        "giftReceiptEligible": true
                    },
                    "sellerId": "F55CDC31AB754BB68FE0B39041159D63",
                    "twoDayShippingEligible": true,
                    "id": "DCFFA990DE7241A8A07014C4C3E880A1",
                    "geoItemClassification": "NETWORK_GEO",
                    "upsellFulfillmentOption": {
                        "displayUpsellForAllCategoriesEnabled": true,
                        "shippingPrice": {},
                        "skyLineAdEnabled": true,
                        "shipMethod": "EXPEDITED",
                        "title": "shipping_title_default",
                        "upsellable": true
                    },
                    "offerFlags": {
                        "s2HOption": true
                    },
                    "consumable": false,
                    "fulfillment": {
                        "hasShippingRestrictions": false,
                        "highlightedShippingOption": {
                            "index": 0,
                            "title": "shipping_title_default"
                        },
                        "upsellShippingOptionIndex": -1,
                        "shippable": true,
                        "freeShippingThresholdPrice": {},
                        "pickupable": false,
                        "locationSurcharge": false,
                        "shippingOptions": [
                            {
                                "fulfillmentDateRange": {},
                                "fulfillmentPriceType": "ORDER",
                                "shipMethod": "EXPEDITED",
                                "fulfillmentPrice": {}
                            },
                            {
                                "fulfillmentDateRange": {},
                                "fulfillmentPriceType": "ITEM",
                                "shipMethod": "RUSH",
                                "fulfillmentPrice": {}
                            }
                        ]
                    },
                    "personalizationData": {},
                    "shipAsIs": false,
                    "status": "FETCHED"
                }
            ],
            "imageList": [
                {
                    "rank": 1,
                    "type": "PRIMARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/88cc5cfa-0902-4909-b9da-5df6cd418fad.6a3261dd042ecb193b183c33254a648e.jpeg"
                    },
                    "assetId": "59FB48929EB24318877CD51B50FE71E7"
                },
                {
                    "rank": 2,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/7b630fed-cd55-4cc1-87d5-90511f65a404.cc3306daa0f9aec7584540410fb80a0d.jpeg"
                    },
                    "assetId": "492D86B8D33040D99619541DFD66B8DD"
                },
                {
                    "rank": 3,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/6c0c863d-3230-49e0-a56a-c919c34155be.8074b9a50ae90f2da122a16c776b81f6.jpeg"
                    },
                    "assetId": "6496DF458C3845AAAE4ACA143C27457C"
                },
                {
                    "rank": 4,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/b7963ead-d764-4535-80b5-a7caae6d3256.19f1f0202b82f615bc12a00d3389f201.jpeg"
                    },
                    "assetId": "57C1D78B47EE4CDAAB13A45E15BA939B"
                },
                {
                    "rank": 5,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/40bf3d24-9538-4b96-9ce2-b863cc8d7305.24781beb4aaa32b5b09de680c0d0de3b.jpeg"
                    },
                    "assetId": "2E754EDEB5054740B2B122EA3BECF522"
                },
                {
                    "rank": 6,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/da340cc5-d7c2-482c-af91-b2065d879b36.817d74e761ec408453dca3b9a5b17543.jpeg"
                    },
                    "assetId": "BDC8747B79E6473090BA0EAC439B080B"
                },
                {
                    "rank": 7,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/05f0ddc8-6f26-47aa-8a16-e910c85ab94d.0d8531d39dd86cd38e81763df320e34f.jpeg"
                    },
                    "assetId": "1A4C252B96F040269BC002106AA97302"
                },
                {
                    "rank": 8,
                    "type": "SECONDARY",
                    "imageAssetSizeUrls": {
                        "default": "https://i5.walmartimages.com/asr/f3aa9642-26c7-4619-83be-1f2837ccc66d.8dfe2114f88e727cbf0b02f3b1b1039d.jpeg"
                    },
                    "assetId": "5884B968C58B4B8BBB4344B2B189CB1E"
                }
            ],
            "status": "FETCHED"
        }
    }
]