#%RAML 1.0 NamedExample
productList:
  [
	{
		"productId": "74PHT29UCA07",
		"usItemId": "384035170",
		"productType": "REGULAR",
		"title": "Crest Scope Outlast Mouthwash, Long Lasting Mint, 1 L, 2 Pack",
		"description": "<li>Keeps breath feeling fresh up to 5x longer vs. brushing alone</li><li>Speak confidently with the #1 fresh breath brand among non-drug mouthwashes** **P&G Calculation based on Nielsen US reported</li>",
		"imageUrl": "https://i5.walmartimages.com/asr/88cc5cfa-0902-4909-b9da-5df6cd418fad.6a3261dd042ecb193b183c33254a648e.jpeg",
		"productPageUrl": "/ip/Crest-Scope-Outlast-Mouthwash-Long-Lasting-Mint-1-L-2-Pack/384035170?wpa_bd=&wpa_pg_seller_id=F55CDC31AB754BB68FE0B39041159D63&wpa_ref_id=wpaqs:O9KIRkt70shqpojaCxcMvQDip15T3cR2Vuh0gHneN1BIYPgQAsp6jmUmkwzZFwGZ9YYJoTUwhNTE3zkULQJUAzYxQjPAB4JWcAmzDoEBnmvSPXTxpF0RJyPFS7zhwBliIjsU8hF9qE6QNDyqgfbmbwu5Co3cc5c7I5nTxoWhyeOu6wSpl3n0tcU76ujZuBrv4t1OCtD9WKsGqRyfP49k9w&wpa_tag=__tag__&wpa_aux_info=__aux_info__&wpa_pos=1&wpa_plmt=__plmt__&wpa_aduid=__aduid__",
		"department": "Personal Care",
		"customerRating": 4.8,
		"numReviews": 99,
		"specialOfferBadge": "bestseller",
		"specialOfferText": "Best Seller",
		"specialOfferLink": "sort=best_seller&cat_id=1005862_1007221_1007360_8361519_5654027&prg=mWeb",
		"sellerId": "F55CDC31AB754BB68FE0B39041159D63",
		"sellerName": "Walmart.com",
		"enableAddToCart": true,
		"canAddToCart": true,
		"cta": [
			"ATC"
		],
		"showPriceAsAvailable": true,
		"seeAllName": "All Dry Mouth Mouthwash",
		"seeAllLink": "sort=best_seller&cat_id=1005862_1007221_1007360_8361519_5654027&prg=mWeb",
		"itemClassId": "1",
		"ppu": {
			"unit": "each",
			"amount": 0.103,
			"currencyCode": "USD"
		},
		"primaryOffer": {
			"offerId": "DCFFA990DE7241A8A07014C4C3E880A1",
			"offerPrice": 6.97,
			"currencyCode": "USD",
			"unitPriceDisplayCondition": "(10.3 ¢/fl oz)"
		},
		"fulfillment": {
			"isS2H": true,
			"isS2S": false,
			"isSOI": false,
			"isPUT": true,
			"s2HDisplayFlags": [
				"THRESHOLD_SHIPPING"
			],
			"s2SDisplayFlags": [
				"PICKUP_TODAY"
			],
			"thresholdAmount": 35.0,
			"thresholdCurrencyCode": "USD"
		},
		"inventory": {
			"availableOnline": true
		},
		"sourceSystem": "WALMART_SC",
		"wpa": {
			"wpa_bd": "",
			"wpa_pg_seller_id": "F55CDC31AB754BB68FE0B39041159D63",
			"wpa_ref_id": "wpaqs:O9KIRkt70shqpojaCxcMvQDip15T3cR2Vuh0gHneN1BIYPgQAsp6jmUmkwzZFwGZ9YYJoTUwhNTE3zkULQJUAzYxQjPAB4JWcAmzDoEBnmvSPXTxpF0RJyPFS7zhwBliIjsU8hF9qE6QNDyqgfbmbwu5Co3cc5c7I5nTxoWhyeOu6wSpl3n0tcU76ujZuBrv4t1OCtD9WKsGqRyfP49k9w",
			"wpa_tag": "__tag__",
			"wpa_aux_info": "__aux_info__",
			"wpa_pos": 1
		},
		"quantity": 3866.0,
		"brand": [
			"Scope"
		],
		"geoItemClassification": "NETWORK_GEO",
		"giftingEligible": true,
		"wmtgPricePerUnitQuantity": "67.6",
		"standardUpc": [
			"00037000771128"
		],
		"isHeartable": true,
		"countPerPack": 2,
		"isWMPlusShipping": true,
		"marketPlaceItem": false,
		"premiumBrand": false,
		"wfsEnabled": false,
		"shippingPassEligible": false,
		"pickupDiscountEligible": false,
		"virtualPack": false,
		"preOrderAvailable": false,
		"blitzItem": false,
		"is_limited_qty": false
	},
	{
		"productId": "41IKU5PHJ3JA",
		"usItemId": "857266140",
		"productType": "VARIANT",
		"title": "Garnier Whole Blends Honey Treasures Shampoo and Conditioner Set, For Damaged Hair, 2 COUNT",
		"description": "Whole Blends Honey Treasures 2pk S&c",
		"imageUrl": "https://i5.walmartimages.com/asr/2630e0c1-b774-4685-bee9-05083ee15869_3.8c8292ef58a1ea96cd94a494c9fc0e3e.jpeg",
		"productPageUrl": "/ip/Garnier-Whole-Blends-Honey-Treasures-Shampoo-and-Conditioner-Set-For-Damaged-Hair-2-COUNT/857266140?wpa_bd=&wpa_pg_seller_id=F55CDC31AB754BB68FE0B39041159D63&wpa_ref_id=wpaqs:DaLkTk2jNgRCOBqL5DKD0S4jUCOWurY2Vl0_IDkInCNIYPgQAsp6jmUmkwzZFwGZ9YYJoTUwhNTE3zkULQJUA8AgUQQQh5PIPqblOqDR6Fe7UT7fPlOMWTZJlQeU_SIUIjsU8hF9qE6QNDyqgfbmbwu5Co3cc5c7I5nTxoWhyeOu6wSpl3n0tcU76ujZuBrv4t1OCtD9WKsGqRyfP49k9w&wpa_tag=__tag__&wpa_aux_info=__aux_info__&wpa_pos=2&wpa_plmt=__plmt__&wpa_aduid=__aduid__",
		"department": "Beauty",
		"customerRating": 4.6,
		"numReviews": 275,
		"specialOfferBadge": "bestseller",
		"specialOfferText": "Best Seller",
		"specialOfferLink": "sort=best_seller&cat_id=1085666_3147628_2103072_8825321&prg=mWeb",
		"sellerId": "F55CDC31AB754BB68FE0B39041159D63",
		"sellerName": "Walmart.com",
		"enableAddToCart": true,
		"canAddToCart": false,
		"cta": [
			"CHOOSE_OPTION"
		],
		"showPriceAsAvailable": true,
		"seeAllName": "All Shampoo and Conditioner",
		"seeAllLink": "sort=best_seller&cat_id=1085666_3147628_2103072_8825321&prg=mWeb",
		"itemClassId": "1",
		"primaryOffer": {
			"offerId": "48961D2DA8864C8B83D758760D0297D4",
			"offerPrice": 5.97,
			"currencyCode": "USD",
			"unitPriceDisplayCondition": "($5.97/oz)"
		},
		"fulfillment": {
			"isS2H": true,
			"isS2S": false,
			"isSOI": false,
			"isPUT": true,
			"s2SDisplayFlags": [
				"PICKUP_TODAY"
			]
		},
		"inventory": {
			"availableOnline": true
		},
		"wpa": {
			"wpa_bd": "",
			"wpa_pg_seller_id": "F55CDC31AB754BB68FE0B39041159D63",
			"wpa_ref_id": "wpaqs:DaLkTk2jNgRCOBqL5DKD0S4jUCOWurY2Vl0_IDkInCNIYPgQAsp6jmUmkwzZFwGZ9YYJoTUwhNTE3zkULQJUA8AgUQQQh5PIPqblOqDR6Fe7UT7fPlOMWTZJlQeU_SIUIjsU8hF9qE6QNDyqgfbmbwu5Co3cc5c7I5nTxoWhyeOu6wSpl3n0tcU76ujZuBrv4t1OCtD9WKsGqRyfP49k9w",
			"wpa_tag": "__tag__",
			"wpa_aux_info": "__aux_info__",
			"wpa_pos": 2
		},
		"quantity": 6812.0,
		"brand": [
			"Garnier"
		],
		"geoItemClassification": "NETWORK_GEO",
		"wmtgPricePerUnitQuantity": "1.00",
		"standardUpc": [
			"00603084565764"
		],
		"isHeartable": false,
		"isWMPlusShipping": true,
		"marketPlaceItem": false,
		"premiumBrand": false,
		"wfsEnabled": false,
		"twoDayShippingEligible": true,
		"shippingPassEligible": false,
		"pickupDiscountEligible": false,
		"virtualPack": false,
		"preOrderAvailable": false,
		"blitzItem": false,
		"is_limited_qty": false
	}
]