#%RAML 1.0 NamedExample
storeList:
  [
	{
		"distance": 0.43,
		"id": 3341,
		"displayName": "Dallas Neighborhood Market",
		"storeType": {
			"id": "4",
			"displayName": "Neighborhood Market"
		},
		"address": {
			"postalCode": "75204",
			"address": "2305 N Central Expy",
			"city": "Dallas",
			"state": "TX",
			"country": "US"
		},
		"operationalHours": {
			"open24Hours": null,
			"todayHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			},
			"tomorrowHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			}
		},
		"geoPoint": {
			"latitude": 32.800647,
			"longitude": -96.794125
		},
		"timeZone": "America/Chicago"
	},
	{
		"distance": 4.76,
		"id": 5823,
		"displayName": "Dallas Supercenter",
		"storeType": {
			"id": "1",
			"displayName": "Supercenter"
		},
		"address": {
			"postalCode": "75231",
			"address": "6185 Retail Rd",
			"city": "Dallas",
			"state": "TX",
			"country": "US"
		},
		"operationalHours": {
			"open24Hours": null,
			"todayHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			},
			"tomorrowHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			}
		},
		"geoPoint": {
			"latitude": 32.862849,
			"longitude": -96.754838
		},
		"timeZone": "America/Chicago"
	},
	{
		"distance": 5.68,
		"id": 2667,
		"displayName": "Dallas Supercenter",
		"storeType": {
			"id": "1",
			"displayName": "Supercenter"
		},
		"address": {
			"postalCode": "75228",
			"address": "7401 Samuell Blvd",
			"city": "Dallas",
			"state": "TX",
			"country": "US"
		},
		"operationalHours": {
			"open24Hours": null,
			"todayHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			},
			"tomorrowHrs": {
				"startHr": "06:00",
				"endHr": "23:00",
				"openFullDay": null
			}
		},
		"geoPoint": {
			"latitude": 32.793803,
			"longitude": -96.689232
		},
		"timeZone": "America/Chicago"
	}
]